language: node_js
node_js:
  - "10"

install:
  - npm install -g yarn
  - yarn
script:
  - yarn docs:build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./docs/.vuepress/dist
  repo: simonwong/simonwong.github.io
  target_branch: master
  on:
    branch: master